title: ProductInfo
type: object
x-tags:
  - products
x-examples:
  example-1:
    ProductId: AlcoReport
    ProductName: Контур.Алко
  example-2:
    ProductId: Bank
    ProductName: Контур.Банк
  example-3:
    ProductId: Prism
    ProductName: Контур.Призма
properties:
  ProductId:
    $ref: ./productid.v1.yaml
  ProductName:
    type: string
    minLength: 1
    pattern: '^[A-Za-z0-9-]+'
required:
  - ProductId
  - ProductName
